### PR TITLE
iOS 9 Minumum Deployment Target

### PR DESCRIPTION
**Pull request by alessioarsuffi**
Let me know if there are issues :) thanks

### CODE REVIEW

**Comment by steve228uk** [comment]
Thanks @alessioarsuffi! 

I'm curious, what prompted the change to the `contentInset`?

**Comment by alessioarsuffi** [comment]
Actually, there is a problem with iOS9, edges of UICollectionView are displayed under ViewController navigationBar. Is this something you've already faced?

**Comment by alessioarsuffi** [comment]
I think it is now solved. I've pinned MSGCollectionView to TopLayoutGuide.bottomAnchor if iOS 9. Tested also with iPhone X - XR to see if Safe Area was still ok.

**Comment by Fabi755** [comment]
What's the status? Why this is not merged? :(

**Comment by sjoness** [comment]
Given the age of iOS 9, I don't think it makes sense to do this now. Moving forward this will be updated to support > iOS 12 or 13

**Pull request closed without merging**
